# fly.toml app configuration file generated for today-fashion-1997 on 2024-02-14T06:25:10+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'today-fashion-1997'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
