default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: todayfashion # PostgreSQLのユーザー名
  password: tofa0129sanga1997 # PostgreSQLのパスワード
  host: localhost

development:
  <<: *default
  database: todayfashion_development

test:
  <<: *default
  database: todayfashion_test

production:
  <<: *default
  database: todayfashion_production
  username: todayfashion
  password: <%= ENV['YOUR_PRODUCTION_DATABASE_PASSWORD'] %>
