default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: todayfashion_development

test:
  <<: *default
  database: todayfashion_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
