default: &default
  source_path: app
  source_entry_path: javascript/packs # ここがエントリーポイントのディレクトリを指す
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true
  additional_paths: [] # resolved_pathsから変更
  cache_manifest: true
  extract_css: true
  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true
  check_yarn_integrity: true

test:
  <<: *default
  compile: true
  cache_manifest: false

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
